name: Build Code with `System.exit(...)` in Java 8 and Java 21

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        java: [8, 21]
    runs-on: ubuntu-latest
    steps:

    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4

    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: maven

    - id: build
      name: Build to show abrupt failure
      shell: bash
      run: |
        # Build
        mvn \
          -Dmaven.source.target=${{ matrix.java }} \
          -Dmaven.compiler.target=${{ matrix.java }} \
          --no-transfer-progress \
          --batch-mode \
          clean verify
